@API_URL = http://localhost:8000/api
# @API_URL = https://evening-island-44720.herokuapp.com
@id = 61a2a0b613273118c43432db
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWJkY2MzNzQzMGM3NDM4NjQ4OThjZjYiLCJyb2xlIjoiQWRtaW4iLCJjbGFzc25hbWUiOiJBZG1pbiIsInBpYyI6ImFzc2V0cy9pbWcvZGVmYXVsdC1hdmF0YXIucG5nIiwibG9naW5QZXJtaXNzaW9uIjp0cnVlLCJpYXQiOjE2NDAzNjQ2MDgsImV4cCI6MTY0MDM2ODIwOH0.F296OLarX864mcoyPhB7pEiQgBhJ5OMa-C9hw_FepGs
@classname = Hawkers

##################################################################

### CHECK SUBSCRIPTION

GET {{API_URL}}/
Content-Type: application/json

### REGISTER USER

POST {{API_URL}}/register
Content-Type: application/json

{
    "classname": "F.D.P.",
    "fullname": "Kelvin Morrison",
    "password": "fridge",
    "phonenumber": "0550653404",
    "email": "kelvin@demo.com",
    "occupation": "Farmer",
    "address": "GA-094887843-12",
    "loginPermission": true,
    "subscriptionPeriod": "2021-12-19T00:00:00.00Z"
}

### USER LOGIN

POST {{API_URL}}/authenticate
Content-Type: application/json

{
    "email": "admin@demo.com",
    "password": "admin"
}

### GET USER DATA

GET {{API_URL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### GET USER BY ID

GET {{API_URL}}/users/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}


##################################################################

### GET MEMBERS BY CLASSNAME

GET {{API_URL}}/user/members/classname/{{classname}}
Content-Type: application/json
Authorization: Bearer {{token}}


##################################################################

### POST PAYMENT

POST {{API_URL}}/user/payment/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userid": "61be0575b7d178134c8f2643",
    "modeOfPayment": "Momo",
    "subscription_plan": "61c0b5638e498b214820e103",
    "currencyCode": "$",
    "phone_number": "0550653404",
    "type": "Monthly",
    "description": "Payment for 1 month"
}

##################################################################

### GET PAYMENT

GET {{API_URL}}/user/payment
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET RESET PASSWORD

GET {{API_URL}}/reset-password/admin@demo.com
Content-Type: application/json

##################################################################

### POST PLAN

POST {{API_URL}}/plan/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Premium Plan",
    "price_per_month": 150,
    "price_per_year": 1600
}

##################################################################

### GET SUBSCRIPTION

GET {{API_URL}}/subscriptions
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### GET PLAN BY NAME

GET {{API_URL}}/plan/doc/Premium Plan
Content-Type: application/json
Authorization: Bearer {{token}}

##################################################################

### POST TASK

POST {{API_URL}}/user/task/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "startdate": "2021-12-24T00:00:00.000Z",
  "_id": "61c5aace8f2f0c1c046d651d",
  "userid": "61bdcc37430c743864898cf6",
  "classname": "Admin",
  "name": "Test Tasks 2",
  "description": "This task has to change it's state when it's 2:00",
  "status": "Completed",
  "enddate": "2021-12-24T16:53:00.000Z"
}
